@IdentityProxy.Api_HostAddress = http://localhost:32787

###

POST {{IdentityProxy.Api_HostAddress}}/api/identity/token
Accept: application/json
Content-Type: application/json

{
  "aud": "62eb2412-f410-4e23-95e7-6a91146bc32c",
  "sub": "99f0cbaa-b3bb-4a77-81a5-e8d17b2232ec"
}

###
